### ISSUE TITLE
Definir horário máximo de reserva

### ISSUE THREAD

**Issue by flpfar** [desenvolvendo-me/tem_acai#47]
Como um estabelecimento, quero definir um horário máximo para solicitação de reservas para que meus clientes saibam quando podem solicitar.

**Comment by Pauloparakleto** [comment]
A definição do horário máximo de reserva se dá no ato da criação de um novo estabelecimento, ou acrescenta-se a um estabelecimento existente? @Arlissonjaques, @flpfar

**Comment by Arlissonjaques** [comment]
Vou conversar com o Felipe sobre essa task. Se você puder @Pauloparakleto , passa para outra task, o mais rápido possível te dou um retorno.

**Comment by flpfar** [comment]
Fala, @Pauloparakleto ! Cara, eu não entendi muito bem sua pergunta. 
Essa alteração deve refletir em todos estabelecimentos, pois será como um campo na hora de salvá-lo. Se a pergunta se dá em relação à sua obrigatoriedade, esse não é um campo obrigatório.
Se ainda ficou dúvida, só dar um toque. :+1:
